/**
 * pis.ts
 * Loads PIs from mapped-pis.json (generated by scripts/map-pis-to-events.js)
 * and exposes a helper to get PIs for a specific DECA event.
 */

import rawPIs from "./mapped-pis.json";

export interface PI {
  id: string;
  text: string;
  cluster: string;
  events: string[];
  /** Derived display code, e.g. "PI-001" */
  code: string;
  /** Cluster name used as a category label */
  category: string;
  /** Fixed at medium — no difficulty metadata in source PDFs */
  difficulty: "high" | "medium" | "low";
}

const ALL_PIS: PI[] = (rawPIs as { id: string; text: string; cluster: string; events: string[] }[]).map(
  (pi, i) => ({
    ...pi,
    code: `PI-${String(i + 1).padStart(4, "0")}`,
    category: pi.cluster,
    difficulty: "medium" as const,
  })
);

/**
 * Returns all PIs relevant to a given event ID.
 * Falls back to all PIs in the matching cluster if the event has no mappings yet.
 */
export function getPIsForEvent(eventId: string): PI[] {
  const mapped = ALL_PIS.filter((pi) => pi.events.includes(eventId));
  return mapped;
}

export { ALL_PIS };
